### ISSUE TITLE
Add ability to provide custom product map.

### ISSUE THREAD

**Issue by anandanand84** [coinbase/coinbase-pro-trading-toolkit#16] opened 2017-09-11 03:28 UTC
Currently there is no way to get feed for other markets if it is not traded in coinbase. Add ability to provide custom product map and reverse product map.

**Comment by CjS77** [comment] 2017-09-20 18:48
By default, if you specify a product id that isn't a GDAX product, it'll pass it on unmodified. This is the intended behaviour at least; if it isn't doing this, then indicate which exchange in particular I need to update.

**Comment by anandanand84** [comment] 2017-09-20 19:15
Agree currently it passes the product unmodified, but it doesnt do any good because now you have two different way of representation of an exchange product, one representation is GDAX format for currency that is in GDAX and another which doesnt have a GDAX product. 

You can take a look at this https://github.com/anandanand84/gdax-tt unique format based on ccxt such a way all products is of one kind. 

It doesn't necessarily have to CCXT format but you have to create maps for all the currency irrespective of whether it is present in one exchange or not. The quickest way I found was to use ccxt where they have everything mapped.

If you would like I can create a pull request.

**Comment by CjS77** [comment] 2017-09-30 13:59
PRs are most welcome

**Comment by drewrothstein** [comment] 2020-01-16 05:51
Hi, we are closing out PRs + Issues as this project is being archived.

**Closed by drewrothstein** 2020-01-16 05:51 UTC
Labels: feature request
