### ISSUE TITLE
websocket error on trader.placeOrder

### ISSUE THREAD

**Issue by breauxx** [coinbase/coinbase-pro-trading-toolkit#121] opened 2017-12-21 04:44 UTC
I have the GDAXfeed stream piped to both trader and book. Book is a LiveOrderBook and is listening for ticker updates and trader is a Trader instance and is listening for order updates. Trader is also used to place an order. Sometimes I run this code and it executes fine, places the order but returns an info message that says "message dropped : expected XXX but recieved XXXXXXXXX" however it keeps on updating the ticker and executing the code. Other times I run the exact same code and it  places the order, but then disconnects from the WSS feed and pauses execution.  XXX and XXXXXXXX in the infor message are different each time. 

var orderplaced : boolean = false;
feed.pipe(book);
feed.pipe(trader);
var order : PlaceOrderMessage = {
            type: 'placeOrder',
            productId: product,
            size: '0.1',
            price: '100', //buy price string goes here after debugging
            side: 'buy',
            orderType: 'limit',
            postOnly: true
        } as PlaceOrderMessage;

..establish the authenticated GDAX feed stream...

//listens to the ticker and then executes an order
book.on('LiveOrderBook.ticker', ((ticker:Ticker) => {
     console.log(ticker.ask.round(2))
     // if the ticker is above a certain point and an order has not yet been placed then place on order
     if (ticker.ask>700 && (!orderplaced)) {
             trader.placeOrder(order);
             orderplaced=true;
     }
});

//the trade never gets executed because the order price is too low but this is for testing the trader listeners
 trader.on('Trader.trade-executed', (msg: TradeExecutedMessage) => {
        logger.log('info', 'Trade executed', JSON.stringify(msg));
        console.log("----------------Trade Executed---------------")
    });

//this one only gets executed if I cancel the orders manually on the website but when it executes I get an
// error and the WSS feed disconnects
 
trader.on('Trader.trade-finalized', (msg: TradeFinalizedMessage) => {
        logger.log('info', 'Order complete', JSON.stringify(msg));
   });

**Comment by mujud** [comment] 2017-12-24 19:04
I had the same issue. Solved it by making sure to disconnect from the feed(feed.disconnect()).
I believe it is caused by force closing the node server without disconnecting from the feed. Once you reconnect again the error happens. The old web-socket connection is still on and conflicts with the new one.

**Comment by rod-farva-sql** [comment] 2018-01-20 03:17
I am seeing the same behavior.  Did you make any progress figuring this out?

**Comment by breauxx** [comment] 2018-01-20 19:59
No, I ended up listening to the 'trader' and 'book' feed streams like I was
doing before but I ended up using the REST API to actually place my orders

 gdax_REST_API.placeOrder(BuyOrderMsg).then((result: LiveOrder) => {
//places the order using REST API

**Comment by jrhite** [comment] 2018-04-20 11:18
i still see the same behavior. any updates?

not sure about your REST API comment. calling `trader.placeOrder(order)` uses the REST API under the hood, not the websocket feed.

**Comment by LikeTheWolf** [comment] 2019-02-19 09:53
This seems to be caused by having the same feed piped to both the book and the trader, the book accidendentally interprets the trader message as a book message in its default message handling logic.

To fix this you can hack the LiveOrder module itself @206 inside "processLevel3Messages" - add the fix:

 // fix for sequencing bug, on open trade the sequence number is not the same as the
        // user specific websocket sequence, mostly likely this refers to the actual server side
        // sequence at gdax and should be ignored (ignore messages meant for the trader caught by the book)
        if (message.type === 'myOrderPlaced') {
            return;
        }

directly above " const sequenceStatus = this.checkSequence(message.sequence);"

This causes the my order placed message to be ignored, this order message is meant for the trader and contains a different sequence number, so the book incorrectly thinks it dropped a message. Hope this helps!

**Comment by LikeTheWolf** [comment] 2019-02-19 10:28
This is caused by the feed being piped to both the book and the trader, the book receives a message meant for the trader and incorrectly believes it has dropped a message as a result...

Make this addition to processLevel3Messages method @200 LiveOrderbook.js /ts /however you are running it:

 /**
     * Processes order messages from order-level books.
     */
    processLevel3Messages(message) {
        // Can't do anything until we get a snapshot
        if (!this.snapshotReceived || !message.sequence) {
            return;
        }

        // fix for sequencing bug, on open trade the sequence number is not the same as the
        // user specific websocket sequence, mostly likely this refers to the actual server side
        // sequence at gdax and should be ignored (ignore messages meant for the trader caught by the book)
        if (message.type === 'myOrderPlaced') {
            return;
        }

        const sequenceStatus = this.checkSequence(message.sequence);
        if (sequenceStatus === SequenceStatus.ALREADY_PROCESSED) {
            return;
        }

**Comment by drewrothstein** [comment] 2020-01-16 05:51
Hi, we are closing out PRs + Issues as this project is being archived.

**Closed by drewrothstein** 2020-01-16 05:51 UTC
